name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: update-readme
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tests
        run: make test

      - name: Update README with repo stats
        run: make update
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md assets/languages.svg
          git diff --staged --quiet || git commit -m "chore: update readme stats"
          git push
